---
title: "GSE165388_gw9"
author: Yuji Okano
date: August 24, 2022
output:
  md_document:
    variant: markdown_github
---

# 01_preprocess

## Objectives
1. preprocessing GSE165388 data

### load data and make seurat object

```{r set-up}
library(dplyr)
library(Matrix)
library(patchwork)
library(Seurat)

raw.data <- Read10X(data.dir = "../../data/gse165388/GSM5032680_GW9/")
data <- CreateSeuratObject(counts = raw.data, project = "GSE165388_GW9", min.cells = 3, min.features = 200)
data
```
### check matrix
```{r, echo=FALSE}
raw.data[c("GAPDH", "NES", "DCX", "TUBB3", "GFAP"), 1:30]
```

### check difference between dense matrix and sparse matix
- dense matrix
```{r, echo=FALSE}
dense.size <- object.size(as.matrix(raw.data))
dense.size
```

## Export raw matrix
```{r}
dir.name <- "../../data/gse165388_processed"

if (! dir.exists(dir.name)) {
  dir.create(dir.name)
}

writeMM(GetAssayData(data), file = paste0(dir.name, "/gw9_raw.mtx"))
capture.output(colnames(GetAssayData(data)),file = paste0(dir.name, "/gw9_raw_samples.txt"))
capture.output(rownames(GetAssayData(data)), file = paste0(dir.name, "/gw9_raw_genes.txt"))
```

---
## QC
```{r}
data[["percent.mt"]] <- PercentageFeatureSet(data, pattern = "^MT-")
```

### visualization
```{r}
VlnPlot(data, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r, fig.dim=c(20, 6), out.width = "400px"}
plot1 <- FeatureScatter(data, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(data, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1
```

```{r}
plot2
```

## filter submatrix
```{r}
data <- subset(data, subset = nFeature_RNA > 200 & nFeature_RNA < 5000 & percent.mt < 20)
```

## Normalization
```{r}
data <- NormalizeData(data, normalization.method = "LogNormalize", scale.factor = 10000)
```

```{r}
dim(GetAssayData(data))
```

## Export Normalized (filtered) matrix
```{r}
dir.name <- "../../data/gse165388_processed"

if (! dir.exists(dir.name)) {
  dir.create(dir.name)
}

writeMM(GetAssayData(data), file = paste0(dir.name, "/gw9_log.mtx"))
capture.output(colnames(GetAssayData(data)),file = paste0(dir.name, "/gw9_log_samples.txt"))
capture.output(rownames(GetAssayData(data)), file = paste0(dir.name, "/gw9_log_genes.txt"))
```

## Export SeuratObject
```{r}
saveRDS(data, file = paste0(dir.name, "/gw9_seuratobject.rds"))
```